services:
    newscoop_editor.configure_menu_listener:
        class: Newscoop\EditorBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments:
            - @translator

    newscoop_editor.lifecyclesubscriber:
        class: Newscoop\EditorBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
            - @fos_oauth_server.client_manager.default
            - @system_preferences_service
        tags:
            - { name: kernel.event_subscriber}

    newscoop_editor.editor_service:
        class: Newscoop\EditorBundle\Services\EditorService
        arguments:  ["@em"]
