services:
    newscoop_editor.configure_menu_listener:
        class: Newscoop\EditorBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments: 
            - @translator

    newscoop_editor.lifecyclesubscriber:
        class: Newscoop\EditorBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}
